name: Substitute values into Tokenised File
description: Substitute GitHub values into a File, matching on specified Token formats.
author: Skylark @ Lambdaspire
inputs:
  file:
    required: true
    description: The file to replace.
  output:
    required: false
    description: An optional alternative output file.
  tokenPatterns:
    required: true
    description: JSON representation of the patterns.
  valuesJson:
    required: true
    description: JSON representation of the valuesJson.
runs:
  using: node20
  main: dist/index.js
branding:
  icon: dollar-sign
  color: gray-dark